-- =====================================================================
-- BARBEARIA LA FÉ - schema usado pelo ADAPTADOR LOCAL de desenvolvimento
-- (sandbox/preview). Em produção o banco oficial é Microsoft SQL Server
-- 2019 (database/02-create-tables.sql) acessado pelo driver `mssql`.
-- Este arquivo mantém a mesma estrutura de tabelas para desenvolvimento.
-- =====================================================================

CREATE TABLE IF NOT EXISTS admins (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)  NOT NULL,
    email         VARCHAR(160)  NOT NULL UNIQUE,
    password_hash VARCHAR(200)  NOT NULL,
    role          VARCHAR(20)   NOT NULL DEFAULT 'OWNER',
    active        SMALLINT      NOT NULL DEFAULT 1,
    created_at    TIMESTAMP(0)  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS customers (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(140)  NOT NULL,
    phone      VARCHAR(30)   NOT NULL,
    email      VARCHAR(160),
    notes      VARCHAR(500),
    active     SMALLINT      NOT NULL DEFAULT 1,
    created_at TIMESTAMP(0)  NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS barbers (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(140)  NOT NULL,
    phone              VARCHAR(30),
    email              VARCHAR(160),
    photo              VARCHAR(400),
    specialty          VARCHAR(200),
    bio                VARCHAR(600),
    commission_percent NUMERIC(5,2)  NOT NULL DEFAULT 40.00,
    active             SMALLINT      NOT NULL DEFAULT 1,
    created_at         TIMESTAMP(0)  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS services (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(140)  NOT NULL,
    description      VARCHAR(600),
    price            NUMERIC(10,2) NOT NULL,
    duration_minutes INT           NOT NULL DEFAULT 30,
    category         VARCHAR(60),
    active           SMALLINT      NOT NULL DEFAULT 1,
    created_at       TIMESTAMP(0)  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS service_barbers (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id INT NOT NULL REFERENCES services(id),
    barber_id  INT NOT NULL REFERENCES barbers(id),
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    CONSTRAINT uq_service_barber UNIQUE (service_id, barber_id)
);

CREATE TABLE IF NOT EXISTS business_hours (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week INT NOT NULL UNIQUE,
    open_time   TIME,
    close_time  TIME,
    is_closed   SMALLINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS barber_hours (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id   INT NOT NULL REFERENCES barbers(id),
    day_of_week INT NOT NULL,
    start_time  TIME,
    end_time    TIME,
    is_closed   SMALLINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP(0),
    CONSTRAINT uq_barber_hours UNIQUE (barber_id, day_of_week)
);

CREATE TABLE IF NOT EXISTS blocked_times (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id  INT REFERENCES barbers(id),
    date       DATE        NOT NULL,
    start_time TIME,
    end_time   TIME,
    reason     VARCHAR(240) NOT NULL,
    type       VARCHAR(20)  NOT NULL DEFAULT 'HORARIO',
    active     SMALLINT     NOT NULL DEFAULT 1,
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS appointments (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      INT NOT NULL REFERENCES customers(id),
    barber_id        INT NOT NULL REFERENCES barbers(id),
    service_id       INT NOT NULL REFERENCES services(id),
    appointment_date DATE        NOT NULL,
    start_time       TIME        NOT NULL,
    end_time         TIME        NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    price            NUMERIC(10,2) NOT NULL,
    payment_method   VARCHAR(20),
    notes            VARCHAR(400),
    created_at       TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS products (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(160)  NOT NULL,
    description   VARCHAR(600),
    price         NUMERIC(10,2) NOT NULL,
    stock         INT           NOT NULL DEFAULT 0,
    minimum_stock INT           NOT NULL DEFAULT 2,
    category      VARCHAR(60),
    image         VARCHAR(400),
    active        SMALLINT      NOT NULL DEFAULT 1,
    created_at    TIMESTAMP(0)  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS product_sales (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     INT NOT NULL REFERENCES products(id),
    barber_id      INT REFERENCES barbers(id),
    customer_id    INT REFERENCES customers(id),
    quantity       INT           NOT NULL DEFAULT 1,
    unit_price     NUMERIC(10,2) NOT NULL,
    total          NUMERIC(10,2) NOT NULL,
    payment_method VARCHAR(20)   NOT NULL DEFAULT 'DINHEIRO',
    created_at     TIMESTAMP(0)  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS commissions (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INT NOT NULL UNIQUE REFERENCES appointments(id),
    barber_id      INT NOT NULL REFERENCES barbers(id),
    base_amount    NUMERIC(10,2) NOT NULL,
    percent        NUMERIC(5,2)  NOT NULL,
    amount         NUMERIC(10,2) NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'PENDENTE',
    paid_at        TIMESTAMP(0),
    created_at     TIMESTAMP(0)  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS commission_payments (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commission_id INT NOT NULL REFERENCES commissions(id),
    barber_id     INT NOT NULL REFERENCES barbers(id),
    amount        NUMERIC(10,2) NOT NULL,
    note          VARCHAR(300),
    paid_by       INT,
    paid_at       TIMESTAMP(0)  NOT NULL DEFAULT now(),
    created_at    TIMESTAMP(0)  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transactions (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(10)  NOT NULL,
    category         VARCHAR(60)  NOT NULL DEFAULT 'OUTROS',
    description      VARCHAR(240) NOT NULL,
    amount           NUMERIC(10,2) NOT NULL,
    payment_method   VARCHAR(20),
    reference_type   VARCHAR(30),
    reference_id     INT,
    transaction_date DATE         NOT NULL DEFAULT CURRENT_DATE,
    created_by       INT,
    created_at       TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reviews (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    INT REFERENCES customers(id),
    appointment_id INT REFERENCES appointments(id),
    customer_name  VARCHAR(140) NOT NULL,
    rating         SMALLINT     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment        VARCHAR(800),
    approved       SMALLINT     NOT NULL DEFAULT 0,
    active         SMALLINT     NOT NULL DEFAULT 1,
    created_at     TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS settings (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key        VARCHAR(60)  NOT NULL UNIQUE,
    value      VARCHAR(400),
    updated_at TIMESTAMP(0)
);

CREATE INDEX IF NOT EXISTS ix_appointments_date ON appointments (appointment_date);
CREATE INDEX IF NOT EXISTS ix_appointments_barber_date ON appointments (barber_id, appointment_date);
CREATE INDEX IF NOT EXISTS ix_appointments_status ON appointments (status);
CREATE INDEX IF NOT EXISTS ix_blocked_times_date ON blocked_times (date);
CREATE INDEX IF NOT EXISTS ix_tx_date ON transactions (transaction_date);
CREATE INDEX IF NOT EXISTS ix_commissions_status ON commissions (status, barber_id);
